Arithmatic Operation

In [ ]:
a=5
b=6
c=a+b
d=a*b
e=a/b
f=a-b
print(a,b,c,d,e,f)
print("sum:", c)

5 6 11 30 0.8333333333333334 -1
sum: 11


In [ ]:
a=4
b=5
if a>b:
  print("a is greater than b")
elif b>c:
  print("b is greater than c")
else:
  print("b is not less than a and c")

In [ ]:
for i in range(1,10):
  print(i)

In [ ]:
for i in range(11,1,-2):
  print(i)

In [ ]:
for i in range(1,20,2):
  print(i)

In [ ]:
i=0
while i<=11:
  print(i)
  i+=1 #this is the increment 



  

Starting to ML:


In [ ]:
import pandas as pd #useful for loading the dataset 
import numpy as np #for performing array

Choose Dataset file from Local Directory


In [ ]:
from google.colab import files
uploaded=files.upload()

Saving ml_sanjay.csv to ml_sanjay.csv


Load dastaset


In [ ]:
dataset=pd.read_csv('ml_sanjay.csv')
print(dataset)

    Age  Salary  Status
0    18   82000       0
1    29   80000       0
2    47   25000       1
3    45   26000       1
4    46   29000       1
5    48   22000       1
6    45   49000       1
7    47   41000       1
8    48   22000       1
9    45   23000       1
10   46   20000       1
11   47   28000       1
12   49   30000       1
13   47   43000       1
14   29   29000       0
15   24   10000       0
16   23   55000       0
17   36   33000       1
18   49   36000       0
19   19   19000       0
20   35   20000       0
21   26   43000       0
22   27   57000       0
23   19   76000       1
24   27   58000       0
25   27   84000       0
26   32  150000       0
27   25   84000       1
28   35  150000       0
29   26   22000       0
30   26   65000       0
31   20   80000       0
32   32   52000       0
33   23   86000       1
34   33   18000       0


Summarize dataset


In [ ]:
print(dataset.shape) #no. of rows and col
print(dataset.head(3)) #top values of data
print(dataset.tail(3))

(35, 3)
   Age  Salary  Status
0   18   82000       0
1   29   80000       0
2   47   25000       1
    Age  Salary  Status
32   32   52000       0
33   23   86000       1
34   33   18000       0


Segregate dataset into x(input/independentvarialbe) & y(output/dependentvariable)

In [ ]:
X=dataset.iloc[:,:2].values
X

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  29000],
       [    48,  22000],
       [    45,  49000],
       [    47,  41000],
       [    48,  22000],
       [    45,  23000],
       [    46,  20000],
       [    47,  28000],
       [    49,  30000],
       [    47,  43000],
       [    29,  29000],
       [    24,  10000],
       [    23,  55000],
       [    36,  33000],
       [    49,  36000],
       [    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  84000],
       [    35, 150000],
       [    26,  22000],
       [    26,  65000],
       [    20,  80000],
       [    32,  52000],
       [    23,  86000],
       [    33,  18000]])

In [ ]:
Y=dataset.iloc[:,-1].values
Y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0])

Splitting Dataset into Train and Test

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=.25,random_state=0)

Feature Scaling 

 we scale our data to make all the features contribute equally to the result

 Fit_Transform-fit method is calculating the mean and variance of each of the features present in our data
 

Transform-Transform method is transforming all the features using the respective mean and variance,

 We want our test data to be a completely new and surprise set for our model
 

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
print(X_train)
print('fdfd')
print(X_test)

[[-0.84829489  1.04165691]
 [-0.66449766  1.04165691]
 [-0.11310599 -1.12761889]
 [-0.2050046  -0.01011317]
 [-0.2050046   3.21093272]
 [-0.75639628  0.41716842]
 [ 1.26537321 -0.99614763]
 [ 1.1734746  -0.30592351]
 [ 1.26537321 -0.99614763]
 [ 0.16258985 -0.63460166]
 [-0.48070044 -0.76607292]
 [-1.30778795  0.91018565]
 [-0.66449766  0.18709372]
 [-0.48070044  0.91018565]
 [ 1.35727182 -0.73320511]
 [ 0.98967737 -0.10871662]
 [-1.39968657  0.77871439]
 [ 1.08157598 -0.76607292]
 [ 1.35727182 -0.53599822]
 [-0.75639628 -0.30592351]
 [-1.39968657 -1.09475108]
 [ 0.98967737 -0.96327982]
 [ 1.1734746  -0.37165914]
 [-1.03209211  1.10739254]
 [ 0.98967737 -0.86467637]
 [-1.49158518  0.97592128]]
fdfd
[[-0.75639628 -0.99614763]
 [ 0.07069124 -1.06188326]
 [-1.03209211  0.08849027]
 [ 0.07069124  3.21093272]
 [-0.66449766  0.1542259 ]
 [-0.9401935  -1.39056141]
 [ 1.08157598 -1.06188326]
 [ 1.1734746  -0.89754418]
 [ 1.1734746  -0.79894074]]


Training


In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression() #loading the alg
model.fit(X_train,y_train)#train 


LogisticRegression()

Predcting


In [ ]:
y_pred=model.predict(X_test)
from sklearn.metrics import accuracy_score
print("Accuracy of the model:{0}%".format(accuracy_score(y_test,y_pred)*100))

Accuracy of the model:88.88888888888889%


Predicting wheather new customer with Age and Salary  will Buy  or Not

In [ ]:
age=int(input("Enter new customer's age:"))
salary=int(input("Enter new customer's salary:"))
newcustomer=[[age,salary]]
result=model.predict(sc.transform(newcustomer))
print(result)
if result ==1:
  print("This new customer will buy the product")
else:
  print("This new customer won't buy")

Enter new customer's age:67
Enter new customer's salary:3333333333
[0]
This new customer won't buy
